### PR TITLE
Fix regex patterns and add minimum version for scikit-image

### PR DESCRIPTION
**Pull request by tabedzki**
This pull request includes two commits. The first commit fixes regex patterns in the code by providing raw annotations for strings with unsupported escape regex sequences. The second commit adds a minimum version requirement for scikit-image in the setup.py file. These changes ensure that the code functions correctly in Python 3.12 and is compatible with the required dependencies.

### CODE REVIEW

**Comment by tabedzki** [comment]
@ethho would you be able to review this?

**Comment by ethho** [comment]
@ttngu207 or @kushalbakshi Do you have time to review? I'm not as familiar with this project.

cc: @tabedzki

**Review by kushalbakshi — APPROVED** [review]
Thanks @tabedzki. I was able to test the tutorial notebook through Codespaces with your changes and it ran through without any issues. I'll merge this right now but hold off on a release since we're planning for one in the coming weeks. You will still be able to use this by installing the repository directly.

**Comment by ttngu207** [comment]
Thanks @tabedzki @kushalbakshi @ethho!

**Pull request merged**
