### PR TITLE
Docstring changes for docs API

### PR DESCRIPTION
**Pull request by kushalbakshi**
I've edited `ephys_acute.py` and `ephys_chronic.py` to test whether the docs API renders correctly for `InsertionLocation`, `ClusteringParamSet`, `Unit`, and `Electrode` tables. In local deployment, the API rendered without issues even before the changes were made, making it difficult to test the changes locally. 

If this results in rendering the API successfully, I will make these changes for all modules and tables that are not covered in this PR. 

Other changes to `ephys_acute.py` and `ephys_chronic.py` were performed by the Black formatter in VSCode.

### CODE REVIEW

**Review by CBroz1 — DISMISSED** [review]
Thanks @kushalbakshi.

In the future, we should separate any blackifying changes into a single commit so that the reviewer can inspect intentional changes separately. I set up a vscode shortcut to toggle format on save - lmk if you'd like help setting that up.

**Comment by kushalbakshi** [comment]
@CBroz1, the merge conflicts in CHANGELOG are resolved now. I tried to address them using GitHub's web interface but I wasn't sure if that would've resulted in a self-merge when resolved so I've resolved conflicts by pulling from upstream and resolving locally. 

> Thanks @kushalbakshi.
> 
> In the future, we should separate any blackifying changes into a single commit so that the reviewer can inspect intentional changes separately. I set up a vscode shortcut to toggle format on save - lmk if you'd like help setting that up.

Also, this makes sense. I will keep that in mind for future commits. And I'll reach out to you separately to set up the shortcut. That would make things a lot easier.

**Review by CBroz1 — APPROVED** [review]

**Comment by kabilar** [comment]
@kushalbakshi Did you mirror the changes to the other `ephys_*` modules?  I may have missed those updates if it was in a separate pull request.

**Comment by kushalbakshi** [comment]
> @kushalbakshi Did you mirror the changes to the other `ephys_*` modules? I may have missed those updates if it was in a separate pull request.

I just went back and looked through the site to double check. Everything seems to be rendering correctly on all ephys modules.

**Pull request merged**
